### ISSUE TITLE
Octopus PPT goto slide

### ISSUE THREAD

**Issue by SimonBick** [bitfocus/companion-module-octopus#8]
The goto slide number function does not work in Octopus Listener

Expected behaviour
When entering a slide number, it should go to that slide, commando is being send, but the listener does nothing

Next and previous does work.

Desktop (please complete the following information):

OS: macOS High Sierra 10.13.6

I saw that this had been raised and closed once, but i am having the same issue.

**Comment by JeffreyDavidsz** [comment]
The octopus listener on Mac is build with aaple script and the go-to does not work. As I understood no updates will come, so this functionality is only for windows. I might add some text in the module for it
